name: Consensus Compliance Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: [self-hosted-ghr, size-xl-x64]
    
    steps:
    - uses: actions/checkout@v4

    - name: Update apt sources and install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnappy-dev libssl-dev python3-dev build-essential
        sudo apt-get install -y libpq-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev libjpeg-dev zlib1g-dev
        dpkg -s libsnappy-dev | grep -q "install ok installed" || exit 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Checkout eth2.0-specs
      uses: actions/checkout@v4
      with:
        repository: ericsson49/eth2.0-specs
        ref: fc-compliance2
        path: eth2.0-specs

    - name: Setup Python environment
      working-directory: eth2.0-specs/tests/generators/fork_choice_generated
      run: |
        uv venv
        . .venv/bin/activate
        uv pip install wheel
        echo "
        GENERATOR_MODE = MODE_MULTIPROCESSING
        " >> ../../core/pyspec/eth2spec/gen_helpers/gen_base/settings.py
        uv pip install -r requirements.txt
        uv pip install --upgrade setuptools

    - name: Run tests
      working-directory: eth2.0-specs/tests/generators/fork_choice_generated
      run: |
        . .venv/bin/activate
        mkdir tests_tiny
        uv run test_gen.py -o tests_tiny --fc-gen-config tiny/test_gen.yaml
        tar -czf tests_tiny.tar.gz tests_tiny

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: eth2.0-specs/tests/generators/fork_choice_generated/tests_tiny.tar.gz