name: Generate Compliance Fork Choice Tests
# TODO: Update the workflow repository to use the canonical repository once PRs are merged in
on:
  workflow_dispatch:
    inputs:
      specs_repo:
        description: 'eth2.0-specs repository URL'
        required: false
        default: 'ericsson49/eth2.0-specs'
        type: string
      specs_ref:
        description: 'eth2.0-specs branch/tag/commit'
        required: false
        default: 'fc-compliance2'
        type: string
      specs_path:
        description: 'Path to clone eth2.0-specs'
        required: false
        default: 'eth2.0-specs'
        type: string

jobs:
  generate:
    name: Generate Compliance Fork Choice Test Cases
    runs-on: [self-hosted-ghr, size-xl-x64]
    
    steps:
    - uses: actions/checkout@v4

    - name: Update apt sources and install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.12-venv python3-pip gcc libsnappy-dev libssl-dev python3-dev python3.12-dev build-essential
        sudo apt-get install -y libpq-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev libjpeg-dev zlib1g-dev
        dpkg -s libsnappy-dev | grep -q "install ok installed" || exit 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Checkout eth2.0-specs
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.specs_repo || 'ericsson49/eth2.0-specs' }}
        ref: ${{ github.event.inputs.specs_ref || 'fc-compliance2' }}
        path: ${{ github.event.inputs.specs_path || 'eth2.0-specs' }}

    - name: Setup Python environment
      working-directory: ${{ github.event.inputs.specs_path || 'eth2.0-specs' }}/tests/generators/fork_choice_generated
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        python3 -m pip --version
        pip3 install ruamel.yaml==0.17.21 wheel setuptools
        pip3 install -r requirements.txt

    - name: Generate test cases
      working-directory: ${{ github.event.inputs.specs_path || 'eth2.0-specs' }}/tests/generators/fork_choice_generated
      run: |
        . .venv/bin/activate
        mkdir tests_tiny
        python3 test_gen.py -o tests_tiny --fc-gen-multi-processing --fc-gen-config tiny/test_gen.yaml

    - name: Upload test cases
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fork-choice-test-cases
        path: ${{ github.event.inputs.specs_path || 'eth2.0-specs' }}/tests/generators/fork_choice_generated/tests_tiny/